### ISSUE TITLE
A new note is always created on startup

### ISSUE THREAD

**Issue by danrabbit** [lainsce/notejot#42] opened 2017-11-13 17:58 UTC
Whenever I open notejot from the applications menu, a new empty note is always created.

To me this behavior is kind of annoying since when I'm opening Notejot I usually just want to see my existing notes and if I wanted to make a new one I would do so from the menu

**Comment by lainsce** [comment] 2017-11-13 18:04
Hmm, I can't reproduce this behavior on Loki (stable & daily). Might be a Juno bug? Some cheeky GTK new thing that doesn't work like it used to? :confused:

**Comment by danrabbit** [comment] 2017-11-13 18:14
Ah yeah that's possible. Confirming that I am in fact running the 17.10 daily franken-Juno builds

**Comment by lainsce** [comment] 2017-11-13 18:52
If so, it might need research, since I use the same tactic of just presenting windows if there are any in the storage/data as many other apps...

**Comment by robertsanseries** [comment] 2017-11-13 20:38
@lainsce I can confirm this problem in loki.

Follow video of how to reproduce the error.
[notejot.mp4.zip](https://github.com/lainsce/notejot/files/1468393/notejot.mp4.zip)

**Comment by lainsce** [comment] 2017-11-13 20:45
@robertsanseries That's a different bug, but thanks for showing it to me, can you file a new issue here so I can track that bug?

**Comment by lainsce** [comment] 2017-11-13 20:51
@danrabbit Could you test from master if your problem was also solved?

**Comment by lainsce** [comment] 2017-11-16 22:13
Fixed in master, will be released on 1.3.6

**Closed by lainsce** 2017-11-16 22:13 UTC
