### ISSUE TITLE
Assorted Suggestions

### ISSUE THREAD

**Issue by elswerky** [lainsce/notejot#82] opened 2018-09-27 12:58 UTC
Please can you add some features to this simple sticky notes??

like 
1-to show icon of app in sticky notes and be able to run at with start up hidden in system tray 
2-add bold , italic ,,,etc fonts 
3-do you know xpad ?? it is a so simple sticky notes like  notejot but has other features (please add the features in xpad in it) 
4-be able to add markers for begginig of lines in notejot like for example adding ✅ or similar markers  for better organizing of notes 
5- now when i open notejot ,,it opens all the notes ,, i don't like that ,, in xpad ,, it opens at startup hidden in system tray and right click on it in system tray or topbar ,, i can choose which already present note to open ,not to open all notes 
6-i like the current size of notejot notes ,, but being unable to re-size it is a limitation ,, so you can keep the current size as default but add the ability to resize notes as we like 
![deepinscreenshot_select-area_20180927150344](https://user-images.githubusercontent.com/26687459/46147717-8fcf9980-c266-11e8-8cac-c641c8bc4495.png)

if i remembered other features which can be added and stll keep notejot simple i will comment or modify this topic 
thx in advance

**Comment by lainsce** [comment] 2018-09-27 13:16
Ok let's go number by number:
1. I can't access the system tray, because it doesn't exist.
2. That I can do, I would suggest opening a new issue just for it.
3. I do know XPad, but I don't know what features to add, please make a new issue with the ones you'd like to see.
4. You can already do it. It's a keystroke away: `(x) or ( )` in the beginning of a line.
5. As in 1., I can't access the system tray, and also, all notes should appear and be selectable via Dock icon.
6. It's by design, if you need more writing space, open a new sticky note, simple as that.

**Comment by elswerky** [comment] 2018-09-27 13:27
ok just for suggestion number (1) ,, yes it doesn't appear in system tray or in topbar 

here this is deepin desktop and as deepin topbar is installed ,, so system tray icons appears in topbar in right side of topbar as i show in screenshot ,,,so system tray in my case is disabled and replaced by topbar icons (you can see in screenshot , there are system tray icons for telegram ,, xpad , copyq , whatsie , ,, emoji keybaord , mailspring 

all these apps are prepared to autostart at boot but they open minimzed to topbar or system tray 

this is what i ask for ,, i don't want if i put notejot to autostart apps to find it opening after boot ,, i just want it open hidden 
this is from xpad preferneces to show it in tray ,,( and this is the features i asked you to have a look at it in xpad beside bold ,italic font, underline fonts ) 
-knotes is a full rich note app but with large  size ,, as i remember one or two features i liked in knotes ,,, i will install it now and tell you here these features if they can be applied to notejot 
thx for your reply 
and keep a note of feaures you are going to add 😂 😂
![deepinscreenshot_select-area_20180927152455](https://user-images.githubusercontent.com/26687459/46148960-8267de80-c269-11e8-9912-d390b38f5647.png)
in system tray

**Comment by elswerky** [comment] 2018-09-27 13:30
as i said closing one note shoudn't close all other notes ,, i will try to recored a video now and see if i can upload here

**Comment by elswerky** [comment] 2018-09-27 13:50
here is a video have a look at it 

[deepin-screen-recorder_Select area_20180927153911.mp4.tar.gz](https://github.com/lainsce/notejot/files/2424350/deepin-screen-recorder_Select.area_20180927153911.mp4.tar.gz)

**Comment by elswerky** [comment] 2018-09-27 14:04
from knotes i like this option which is `insert checkmark`  ,, if you can add similar option would be nice 


![deepinscreenshot_select-area_20180927160235](https://user-images.githubusercontent.com/26687459/46151365-e2ad4f00-c26e-11e8-8250-8ec324f51861.png)

**Comment by lainsce** [comment] 2018-09-27 14:48
Yes so let's understand each other:
- You want Notejot to be a background app. That's not allowed in elementary OS, due to having **no** system tray for the app to be accessed from.
- Sadly, Pantheon of elementary OS, which is Notejot's primary Desktop Environment, not Deepin, **doesn't** have that place you have Mailspring, Whatsie, etc.
- So I can't just tell it to be in a tray, because _it doesn't exist_, and it would be _very strange_ for me to predict that it's staying there.
- Notejot **isn't** an universal app, it's supposed to only work in elementary OS, so expect it to work as it should there.
- Notejot was designed so you'd use it for quick annotations, **not** full on documents or big notes. If you need more space, _open up a new note_.

Now, for "Closing one note shouldn't close all others":
- This I can't fix because one of the notes is always the parent process governing all other notes, or otherwise Notejot would be a big app with each note in a grid. I can't fix this.

And finally, for the checkmark/bold/italic/etc options:
- I'll find a way to incorporate these features in Notejot, don't worry.

**Comment by elswerky** [comment] 2018-09-27 14:56
ok i understand you 
and you made notejot primary for elemetary os 
now xpad is just 90 kb ,,nearly like notejot ,,but what will happen if you insalled it on elemetary os ?? it will works as it is supposted without system tray icon ,, but if you installed it on another desktop it will have its system tray  icon ,, this is what i meant 
thx for your reply 
[xpad.tar.gz](https://github.com/lainsce/notejot/files/2424622/xpad.tar.gz)

**Comment by lainsce** [comment] 2018-09-27 15:47
Yes, but I'm saying is that I can't add a system tray icon to Notjot, it's out-of-spec.
I'm closing this issue. Make new ones for each suggestion or not, your choice.
I'm not going to bow down Notejotejot for Deepin, it's not my job.

**Closed by lainsce** 2018-09-27 15:47 UTC

**Comment by elswerky** [comment] 2018-09-27 15:50
ok ,,thx,, i will make another issue for suggestions we agree that they can be add 
thank you for your patience

**Comment by morgenman** [comment] 2020-09-15 23:01
@lainsce, your response is with great patience. The entitlement and demanding nature of this request is incredible. As someone who no longer uses elementary, I also would benefit from not having this show up in my running apps bar and workspace preview, but I wouldn't deign to demand it from you. Hell if I can't figure out how to do it with my window manager I might fork it myself.
